version: '3'

services:
  my-service:
    image: ${REPO}my.service:${VERSION}
    container_name: my-service
    networks:
      - backend_network
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SOME_VARIABLE: ${SOME_ENV_VARIABLE}

  nginx-service:
    image: nginx
    environment:
      SOME_VARIABLE: ${SOME_ENV_VARIABLE}

networks:
  backend_network: