FROM python:2.7-slim

COPY ./pythonSnippet.py ./src/pythonSnippet.py

LABEL version="1.0"
LABEL owner="example owner"
LABEL org.opencontainers.image.version="1.0.0"
LABEL license="example:license"

ENTRYPOINT python ./src/pythonSnippet.py