FROM node

RUN mkdir -p /app

WORKDIR /app

COPY package.json package-lock.json /app/
COPY proxy.config.json /app/

RUN ["npm", "config", "set", "@dips:registry", "http://nuget.org/npm/"]

RUN ["npm", "install"]

COPY . /app

EXPOSE 4200/tcp

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]
