# Run "docker build -f Dockerfile -t <docker_image> ." in powershell to build this Dockerfile locally.

FROM microsoft/dotnet:2.0-sdk AS build
WORKDIR /src
COPY . .

ARG VERSION=1.0.0
ARG NUGET_FEED

RUN dotnet pack --configuration Release /p:Version=${VERSION} /p:PackageVersion=${VERSION}

RUN ls Implementations/DIPS.*/bin/Debug/*.${VERSION}.nupkg | xargs -I % sh -c 'dotnet nuget push % -s ${NUGET_FEED}'
RUN ls Contracts/DIPS.*/bin/Debug/*.${VERSION}.nupkg | xargs -I % sh -c 'dotnet nuget push % -s ${NUGET_FEED}'
RUN ls Interfaces/DIPS.*/bin/Debug/*.${VERSION}.nupkg | xargs -I % sh -c 'dotnet nuget push % -s ${NUGET_FEED}'
